### ISSUE TITLE
Issue updating/merging fork

### ISSUE THREAD

**Issue by Sourenics** [cybrxkhan/VIET-Events-for-CK3#10]
Hi! I tried to update my fork but Github told me there were some conflicts. How can I deal with it?

Thanks!!

**Comment by cybrxkhan** [comment]
Hey there! To be honest I'm not really good with GitHub beyond the basics (I don't have any background in programming other than an intro class in HS), so I'm not really sure what needs to be done, but I did find this after doing a quick google search, don't know if it will help: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github

Would it also be possible for you to manually copy and paste some of the changes from my version to yours so they're in alignment, given the main conflicting files would just be the localizations? (Not sure if that would help though, just spitballing here)

**Comment by Sourenics** [comment]
It looks like you deleted somse lines on the update and now there are some conflicts, but I'm trying to manually fix it, wish me luck haha.
I'm also a newbie here on github!

**Comment by Sourenics** [comment]
Oh, found something... Take a look for example on the `viet_modifiers_l_spanish` file

You have some duplicated codes, for example, you have two lines named `VIET_haunted_by_ghost_for_sin`

**Comment by cybrxkhan** [comment]
Got it, let me quickly change them and see if that helps.
