### ISSUE TITLE
what is “XXX” ?

### ISSUE THREAD

**Issue by wuming123** [cybrxkhan/VIET-Events-for-CK3#37]
I think a lot of places are "XXX". What is this?

**Comment by cybrxkhan** [comment]
It's a habit of mine where I leave a lot of them in the code as placeholders so I don't have to keep copy and pasting lines when I make localization for new events. If you're seeing that in-game though that would probably be a bug.

**Comment by wuming123** [comment]
okey,i see "xxx" in the game,so this is error?

**Comment by cybrxkhan** [comment]
Are you using the Spanish or Chinese version? It's possible I might have forgot to put in a placeholder for a few (events not translated yet will show up as the default English as placeholder). If it's not for either of those languages and for a language with a separate translation sub-mod, the translator may have not gotten to translating some  events yet.

**Comment by wuming123** [comment]
I use the simp_chinese

**Comment by cybrxkhan** [comment]
Does it happen for all or many events, or only a few? If it's all and many events try redownloading and reinstlaling the mod (if using the manual version), or unsubscribing and re-subscribing if using the Steam version. If it's a few events, it's probably a few events on our end that are missing localizations then, though some screenshots would help if you have any.

**Comment by wuming123** [comment]
ok

**Comment by wuming123** [comment]
![5IX@H8{@(DU(5P 4`8}YOMM](https://user-images.githubusercontent.com/12251465/95604360-16402800-0a8a-11eb-998e-117b56676358.png)

**Comment by cybrxkhan** [comment]
Ok the screenshot helps, thanks! It seems like I forgot to add in the placeholder English text for a few events that haven't been translated yet. I'll upload a hotfix for that later tonight in a couple hours my time.
